const GHOSTS = [
  { nameJa: 'スピリット',      name: 'Spirit',       evidence: ['EMF', 'SB', 'GW']   },
  { nameJa: 'レイス',          name: 'Wraith',        evidence: ['EMF', 'SB', 'DOTS'] },
  { nameJa: 'ファントム',       name: 'Phantom',       evidence: ['SB', 'UV', 'DOTS']  },
  { nameJa: 'ポルターガイスト', name: 'Poltergeist',   evidence: ['SB', 'UV', 'GW']    },
  { nameJa: 'バンシー',         name: 'Banshee',       evidence: ['UV', 'GO', 'DOTS']  },
  { nameJa: 'ジン',             name: 'Jinn',          evidence: ['EMF', 'UV', 'FT']   },
  { nameJa: 'メアー',           name: 'Mare',          evidence: ['SB', 'GO', 'GW']    },
  { nameJa: 'レヴナント',       name: 'Revenant',      evidence: ['GO', 'GW', 'FT']    },
  { nameJa: 'シェード',         name: 'Shade',         evidence: ['EMF', 'GW', 'FT']   },
  { nameJa: 'デーモン',         name: 'Demon',         evidence: ['UV', 'GW', 'FT']    },
  { nameJa: '幽霊',             name: 'Yurei',         evidence: ['GO', 'FT', 'DOTS']  },
  { nameJa: '鬼',               name: 'Oni',           evidence: ['EMF', 'FT', 'DOTS'] },
  { nameJa: '妖怪',             name: 'Yokai',         evidence: ['SB', 'GO', 'DOTS']  },
  { nameJa: 'ハントゥ',         name: 'Hantu',         evidence: ['UV', 'GO', 'FT']    },
  { nameJa: '御霊',             name: 'Goryo',         evidence: ['EMF', 'UV', 'DOTS'] },
  { nameJa: 'マイリング',       name: 'Myling',        evidence: ['EMF', 'UV', 'GW']   },
  { nameJa: '怨霊',             name: 'Onryo',         evidence: ['SB', 'GO', 'FT']    },
  { nameJa: 'ツインズ',         name: 'The Twins',     evidence: ['EMF', 'SB', 'FT']   },
  { nameJa: '雷獣',             name: 'Raiju',         evidence: ['EMF', 'GO', 'DOTS'] },
  { nameJa: '化け狐',           name: 'Obake',         evidence: ['EMF', 'UV', 'GO']   },
  { nameJa: 'ミミック',         name: 'The Mimic',     evidence: ['SB', 'UV', 'FT']    },
  { nameJa: 'モーロイ',         name: 'Moroi',         evidence: ['SB', 'GW', 'FT']    },
  { nameJa: 'デオヘン',         name: 'Deogen',        evidence: ['SB', 'GW', 'DOTS']  },
  { nameJa: 'セーイ',           name: 'Thaye',         evidence: ['GO', 'GW', 'DOTS']  },
  { nameJa: 'ダヤン',           name: 'Dayan',         evidence: ['EMF', 'GO', 'SB']   },
  { nameJa: 'ガルル',           name: 'Gallu',         evidence: ['EMF', 'UV', 'SB']   },
  { nameJa: 'オバンボ',         name: 'Obambo',        evidence: ['GW', 'UV', 'DOTS']  },
  { nameJa: 'アスワング',       name: 'Aswang',        evidence: ['FT', 'GW', 'DOTS']  },
  { nameJa: 'コルモス',         name: 'Kormos',        evidence: ['GO', 'SB', 'UV']    },
];

const ghostId = g => g.name.toLowerCase().replace(/ /g, '-');
